name: Build & Push - Release
# Automatically builds and pushes a multi-platform image based on the repo's newest release and tags it both as latest and with the version number of the release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PA_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            BUILD_DATE=${{ github.event.repository.updated_at }}
            VERSION=${{ github.event.release.tag_name }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/kepubify-automated:${{ github.event.release.tag_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/kepubify-automated:latest

          platforms: linux/amd64,linux/arm64